# Generated by Django 5.0.6 on 2026-09-04 15:19

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('honorific', models.CharField(default='الشيخ سيدي', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('short_bio', models.CharField(blank=True, max_length=300)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=apps.core.models.UploadTo('scholars'))),
                ('is_current_sheikh', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
