# Generated by Django 5.0.6 on 2026-09-04 15:19

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholars', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('kind', models.CharField(choices=[('series', 'سلسلة'), ('annual', 'إصدار سنوي'), ('album', 'ألبوم')], default='series', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to=apps.core.models.UploadTo('collections'))),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=270, unique=True)),
                ('content_type', models.CharField(choices=[('lecture', 'محاضرة'), ('lesson', 'درس'), ('poem', 'قصيدة / مديح'), ('video', 'فيديو'), ('audio', 'صوتية'), ('book', 'كتاب'), ('pdf', 'ملف PDF'), ('article', 'مقال')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], db_index=True, default='draft', max_length=12)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.core.models.UploadTo('thumbnails'))),
                ('language', models.CharField(default='ar', max_length=5)),
                ('youtube_url', models.URLField(blank=True)),
                ('youtube_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('media_file', models.FileField(blank=True, upload_to=apps.core.models.UploadTo('media'))),
                ('pdf_file', models.FileField(blank=True, upload_to=apps.core.models.UploadTo('pdf'))),
                ('release_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='taxonomy.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='dorouss.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='taxonomy.occasion')),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='scholars.scholar')),
                ('tags', models.ManyToManyField(blank=True, related_name='contents', to='taxonomy.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('audio', 'صوت'), ('video', 'فيديو'), ('image', 'صورة'), ('attachment', 'مرفق')], max_length=15)),
                ('file', models.FileField(upload_to=apps.core.models.UploadTo('media_center'))),
                ('duration', models.DurationField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='dorouss.content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.core.models.UploadTo('pdf_library'))),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.models.UploadTo('pdf_covers'))),
                ('pages_count', models.PositiveIntegerField(default=0)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('extracted_text', models.TextField(blank=True, editable=False)),
                ('processing_status', models.CharField(default='pending', max_length=10)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_document', to='dorouss.content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
